# Dependencies
markdown: redcarpet
pygments: true

# Setup
title: AltGSG
tagline: 'A redesign of the Guardian Style Guide by Roger Hutchings'
description: 'A redesign of the <a href="http://guardian.co.uk/styleguide/" target="_blank">Guardian Style Guide</a>, inspired by some of the better examples of API documentation. Made by <a href="https://twitter.com/drrogg" target="_blank">@drrogg</a>.'

# Custom vars
version: 1.0.0
repo: https://github.com/rogerhutchings/styleguide
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'config.rb', 'README.md']
